variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - deploy

build:
    image: node:6.17.1
    stage: build
    before_script:
        - cd themes/even/
        - yarn install
    script:
        - yarn build
    artifacts:
        paths:
            - themes/even
    only:
        - master
    cache:
        paths:
            - node_modules/
            - .yarn

# deploy:
#     image: registry.gitlab.com/pages/hugo:latest
#     stage: deploy
#     script:
#         - hugo
#     artifacts:
#         paths:
#             - public
#     only:
#         - master
