variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - deploy

build:
    image: node:6.17.1
    stage: build
    script:
        - cd themes/even
        - npm i
        - npm build
    artifacts:
        paths:
            - themes/even
    only:
        - master
