variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - setup
    - build
    - deploy

setup:
    image: node:6.17.1
    stage: setup
    before_script:
        - cd themes/even/
        - yarn install
    script:
        - yarn build
    artifacts:
        paths:
            - themes/even/
    only:
        - master
    cache:
        paths:
            - node_modules/
            - .yarn

build:
    image: registry.gitlab.com/pages/hugo/hugo_extended:latest
    stage: build
    script:
        - hugo
    artifacts:
        paths:
            - public/
    only:
        - master
    dependencies:
        - setup

deploy:
    image: node:latest
    stage: deploy
    before_script:
        - npm i -g netlify-cli
    script:
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    only:
        - master
    dependencies:
        - build
