language: ruby
rvm:
- 2.2.2
install:
- nvm install
- npm install --global amphtml-validator resume-cli
- bundle install
- make
script:
- bundle exec htmlproofer ./_site --disable-external --allow-hash-href --file-ignore /resume.html/
- find _site -type f -name '*.html' -not -name 'resume.html' | xargs -n 1 amphtml-validator
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: dsdeiz
  - EMAIL: qwertyuiop123ph@gmail.com
  - secure: ZWfI+IADvnwQfFnh0CihSJUV6Jlsof0fxpw9CgtJhvj0Wsms+geH0KE3pEeK7IlKtmwmDifYxvHDU8dsBMLMlIbLr1Qnm6oPEoz8AXKIQr1xoblhTfgc0RPmUyAFcsA/jquXso8FM/aNJ9XygpdmAklJI1YKqbPlMzHfy+ENh+s=
  - TRAVIS_NODE_VERSION: 4.2.1
