baseURL = "https://blog.strict-panda.com"
title = "Strict Panda"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-149834650-1"
theme = "hugo-theme-chunky-poster"
summaryLength = 20

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  description = "Random thoughts and ramblings."
  homepageImage = "/images/homepage-image.jpg"

  [params.social]
    rss = true
    email = "me@strict-panda.com"
    facebook = ""
    twitter = ""
    linkedin = ""
    stack-overflow = ""
    instagram = ""
    github = ""
    weibo = ""
    medium = ""
    pinterest = ""
    reddit = ""
    gitlab = "https://gitlab.com/virtualcursor"
    mastodon = ""
    keybase = ""

  [params.prismJS]
    enable = true
    theme = ""

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[outputs]
home = ["HTML", "RSS", "JSON"]
