orbs:
  hugo: circleci/hugo@0
  node: circleci/node@1.1
  aws-s3: circleci/aws-s3@1
version: 2.1

jobs:
  images:
    docker:
      - image: circleci/python:2.7
    steps:
      - aws-s3/copy:
          from: 's3://strict-panda-blog'
          to: images
          arguments: --recursive
      - persist_to_workspace:
          root: .
          paths:
            - images
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          at: ~/images
      - checkout
      - run: cp -r ~/images/images/* content/images
      - run:
          command: |
            if [ -f ".gitmodules" ]; then
              git submodule sync
              git submodule update --init --recursive
            fi
          name: Checkout Submodules if Needed
      - hugo/hugo-build:
          extra-flags: '--minify --quiet'
      - persist_to_workspace:
          root: .
          paths:
            - public
            - netlify.toml
  deploy:
    executor:
      name: node/default
      tag: '13.1.0'
    working_directory: ~/site
    steps:
      - attach_workspace:
          at: ~/site
      - run: npm i netlify-cli
      - run: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --message "Deploy via Circle CI."

workflows:
  main:
    jobs:
      - images
      - build:
          requires:
            - images
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
