orbs:
  hugo: circleci/hugo@0
  node: circleci/node@1.1
version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - hugo/hugo-build
      - persist_to_workspace:
          root: .
          paths:
            - public
            - netlify.toml
  deploy:
    executor:
      name: node/default
      tag: '13.1.0'
    working_directory: ~/site
    steps:
      - attach_workspace:
          at: ~/site
      - run: npm i netlify-cli
      - run: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --message "Deploy via Circle CI."

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
